#include <stdint.h>
#include <math.h>
#include <hardware.h>
#include <bcm2708_chip/aux_io.h>
#include <test-helpers.h>
#include <system-helpers.h>

void setup_pll() {
  A2W_XOSC_CTRL |= A2W_PASSWORD | A2W_XOSC_CTRL_PLLCEN_SET;

  A2W_PLLC_FRAC = A2W_PASSWORD | 87380;
  A2W_PLLC_CTRL = A2W_PASSWORD | 52 | 0x1000;

  A2W_PLLC_ANA3 = A2W_PASSWORD | 0x100;
  A2W_PLLC_ANA2 = A2W_PASSWORD | 0x0;
  A2W_PLLC_ANA1 = A2W_PASSWORD | 0x144000;
  A2W_PLLC_ANA0 = A2W_PASSWORD | 0x0;

  CM_PLLC = CM_PASSWORD | CM_PLLC_DIGRST_SET;

  /* hold all */
  CM_PLLC = CM_PASSWORD | CM_PLLC_DIGRST_SET |
    CM_PLLC_HOLDPER_SET | CM_PLLC_HOLDCORE2_SET |
    CM_PLLC_HOLDCORE1_SET | CM_PLLC_HOLDCORE0_SET;

  A2W_PLLC_DIG3 = A2W_PASSWORD | 0x0;
  A2W_PLLC_DIG2 = A2W_PASSWORD | 0x400000;
  A2W_PLLC_DIG1 = A2W_PASSWORD | 0x5;
  A2W_PLLC_DIG0 = A2W_PASSWORD | 52 | 0x555000;

  A2W_PLLC_CTRL = A2W_PASSWORD | 52 | 0x1000 | A2W_PLLC_CTRL_PRSTN_SET;

  A2W_PLLC_DIG3 = A2W_PASSWORD | 0x42;
  A2W_PLLC_DIG2 = A2W_PASSWORD | 0x500401;
  A2W_PLLC_DIG1 = A2W_PASSWORD | 0x4005;
  A2W_PLLC_DIG0 = A2W_PASSWORD | 52 | 0x555000;

  A2W_PLLC_CORE0 = A2W_PASSWORD | 2;

  CM_PLLC = CM_PASSWORD | CM_PLLC_DIGRST_SET |
    CM_PLLC_HOLDPER_SET | CM_PLLC_HOLDCORE2_SET |
    CM_PLLC_HOLDCORE1_SET | CM_PLLC_HOLDCORE0_SET | CM_PLLC_LOADCORE0_SET;

  CM_PLLC = CM_PASSWORD | CM_PLLC_DIGRST_SET |
    CM_PLLC_HOLDPER_SET | CM_PLLC_HOLDCORE2_SET |
    CM_PLLC_HOLDCORE1_SET | CM_PLLC_HOLDCORE0_SET;

  CM_PLLC = CM_PASSWORD | CM_PLLC_DIGRST_SET |
    CM_PLLC_HOLDPER_SET | CM_PLLC_HOLDCORE2_SET |
    CM_PLLC_HOLDCORE1_SET;

  CM_VPUCTL = CM_PASSWORD | CM_VPUCTL_FRAC_SET | CM_SRC_OSC | CM_VPUCTL_GATE_SET;
  CM_VPUDIV = CM_PASSWORD | (4 << 12);
  CM_VPUCTL = CM_PASSWORD | CM_SRC_PLLC_CORE0 | CM_VPUCTL_GATE_SET;
  CM_VPUCTL = CM_PASSWORD | CM_SRC_PLLC_CORE0 | CM_VPUCTL_GATE_SET | 0x10; /* ENAB */

  CM_TIMERDIV = CM_PASSWORD | (19 << 12) | 819;
  CM_TIMERCTL = CM_PASSWORD | CM_SRC_OSC | 0x10;
}
